# render.yaml
services:
  - type: web
    name: short_link_service
    env: ruby
    plan: free
    region: oregon  # You can choose your region (e.g., oregon, frankfurt, etc.)
    buildCommand: |
      bundle install
      bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        value: sqlite3://storage/production.sqlite3
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false  # You will manually set this in Render dashboard

databases:
  - name: rails-db
    region: oregon  # Should match the region for your web service
    plan: free
    engine: postgres  # This will be used in production as SQLite might not scale well
